# -*- coding: utf-8 -*-
"""final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SkF9UoqKegeGh0DfGZm4rXoYEsHt26mI
"""

class Library:
    def __init__(self):
        self.file = open("books.txt", "a+")
    def __del__(self):
        self.file.close()
    def list_books(self):
        self.file.seek(0)
        bookss = self.file.read().splitlines()
        if not bookss:
            print("Bu listede hiç kitap bulunmamaktadır.")
            return
        print("Kitaplar:")
        for book in bookss:
            book_info = book.split(",")
            print(f"Başlık: {book_info[0]}, Yazar: {book_info[1]}, Çıkış tarihi: {book_info[2]}, Sayfa Sayısı: {book_info[3]}")
    def add_book(self):
        title = input("Kitap başlığını girin: ")
        author = input("Kitap yazarını girin: ")
        release_year = input("Yayın yılı girin: ")
        num_pages = input("Sayfa sayısını girin: ")
        book_info = f"{title},{author},{release_year},{num_pages}\n"
        self.file.write(book_info)
        print("Kitap başarıyla eklendi.")
    def remove_book(self):
        title = input("Silmek istediğiniz kitabın adını girin: ")
        self.file.seek(0)
        books = self.file.readlines()
        new_books = []
        found = False
        for book in books:
            if title in book:
                found = True
            else:
                new_books.append(book)
        if not found:
            print("Seçtiğiniz kitap ismi bulunamadı.")
            return
        self.file.seek(0)
        self.file.truncate()
        self.file.writelines(new_books)
        print("Kitap başarıyla silindi.")

lib = Library()
while True:
    print("\n*** MENÜ ***")
    print("1) Kitapları Listele")
    print("2) Kitap Ekle")
    print("3) Kitap Sil")
    print("4) Çıkış")
    seçim = input("Seçiminizi girin: ")
    if seçim == '1':
        lib.list_books()
    elif seçim == '2':
        lib.add_book()
    elif seçim == '3':
        lib.remove_book()
    elif seçim == '4':
        break
    else:
        print("Geçersiz seçenek. Lütfen geçerli bir seçenek girin.")